"""User.payment_token and Report.time_expire

Revision ID: 156febd50cdd
Revises: 1867b46d09e6
Create Date: 2015-04-15 15:21:24.822014

"""

# revision identifiers, used by Alembic.
revision = '156febd50cdd'
down_revision = '1867b46d09e6'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('time_expire', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('payment_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('time_next_payment', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_next_payment')
    op.drop_column('user', 'payment_token')
    op.drop_column('report', 'time_expire')
    ### end Alembic commands ###
