"""Account remote_data, remote_id, config

Revision ID: 1867b46d09e6
Revises: 4c2d27b91e10
Create Date: 2014-09-27 15:34:07.518044

"""

# revision identifiers, used by Alembic.
revision = '1867b46d09e6'
down_revision = '4c2d27b91e10'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('config', sa.LargeBinary(), nullable=True))
    op.add_column('account', sa.Column('remote_data', sa.LargeBinary(), nullable=True))
    op.add_column('account', sa.Column('remote_id', sa.String(), nullable=True))
    op.create_index('ix_account_service_remote_id', 'account', ['service', 'remote_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_service_remote_id', table_name='account')
    op.drop_column('account', 'remote_id')
    op.drop_column('account', 'remote_data')
    op.drop_column('account', 'config')
    ### end Alembic commands ###
