"""Report.next_preferred

Revision ID: 2997080bf164
Revises: 2ca4416c718a
Create Date: 2013-11-05 11:46:37.873153

"""

# revision identifiers, used by Alembic.
revision = '2997080bf164'
down_revision = '2ca4416c718a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('time_created', sa.DateTime(), nullable=False),
        sa.Column('seconds_elapsed', sa.Float(), nullable=True),
        sa.Column('num_recipients', sa.Integer(), nullable=True),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('display_name', sa.Unicode(), nullable=True),
        sa.Column('report_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.Enum(), nullable=True),
        sa.Column('remote_id', sa.String(), nullable=True),
        sa.Column('subject', sa.Unicode(), nullable=True),
        sa.Column('body', sa.UnicodeText(), nullable=True),
        sa.Column('access_token', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    new_columns = [
        sa.Column('time_preferred', sa.DateTime(), nullable=True),
        sa.Column('type', sa.Integer(), nullable=True, default=2),
    ]
    for column in new_columns:
        op.add_column('report', column)
    ### end Alembic commands ###

    table_view = table('report', *new_columns)

    op.execute(
        table_view.update().values({'type': 2})
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'type')
    op.drop_column('report', 'time_preferred')
    op.drop_table('report_log')
    ### end Alembic commands ###
