"""Account.remote_data

Revision ID: 2bbeead8cff9
Revises: 3bcad835ee23
Create Date: 2014-09-14 13:34:52.623001

"""

# revision identifiers, used by Alembic.
revision = '2bbeead8cff9'
down_revision = '3bcad835ee23'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('remote_data', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'remote_data')
    ### end Alembic commands ###
