"""User.display_name

Revision ID: 2ca4416c718a
Revises: b8252809387
Create Date: 2013-10-26 12:33:58.833419

"""

# revision identifiers, used by Alembic.
revision = '2ca4416c718a'
down_revision = 'b8252809387'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    ### end Alembic commands ###
