"""Webhook and Account.remote_id

Revision ID: 3bcad835ee23
Revises: 4c2d27b91e10
Create Date: 2014-09-14 12:04:12.148012

"""

# revision identifiers, used by Alembic.
revision = '3bcad835ee23'
down_revision = '4c2d27b91e10'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('service', sa.Enum(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], [u'account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_account_id'), 'webhook', ['account_id'], unique=False)
    op.add_column('account', sa.Column('remote_id', sa.String(), nullable=True))
    op.create_index('ix_account_service_remote_id', 'account', ['service', 'remote_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_service_remote_id', table_name='account')
    op.drop_column('account', 'remote_id')
    op.drop_index(op.f('ix_webhook_account_id'), table_name='webhook')
    op.drop_table('webhook')
    ### end Alembic commands ###
