"""User.payment_token and Account.time_revive

Revision ID: 48a40bc12d57
Revises: 1867b46d09e6
Create Date: 2015-03-23 13:27:24.586722

"""

# revision identifiers, used by Alembic.
revision = '48a40bc12d57'
down_revision = '1867b46d09e6'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('time_revive', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_account_time_revive'), 'account', ['time_revive'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_time_revive'), table_name='account')
    op.drop_column('account', 'time_revive')
    ### end Alembic commands ###
