"""Report.config

Revision ID: 67f8ec8554
Revises: d011a623de5
Create Date: 2013-11-29 11:04:53.990944

"""

# revision identifiers, used by Alembic.
revision = '67f8ec8554'
down_revision = 'd011a623de5'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('config', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'config')
    ### end Alembic commands ###
