"""ReportLog.time_sent

Revision ID: d011a623de5
Revises: 27e9e1541270
Create Date: 2013-11-28 18:22:57.884681

"""

# revision identifiers, used by Alembic.
revision = 'd011a623de5'
down_revision = '27e9e1541270'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_log', sa.Column('time_sent', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_log', 'time_sent')
    ### end Alembic commands ###
