"""Account.config

Revision ID: fa4be78941e
Revises: 2bbeead8cff9
Create Date: 2014-09-15 16:42:13.573571

"""

# revision identifiers, used by Alembic.
revision = 'fa4be78941e'
down_revision = '2bbeead8cff9'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook')
    op.add_column('account', sa.Column('config', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'config')
    op.create_table('webhook',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.Column('account_id', sa.INTEGER(), nullable=True),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('service', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], [u'account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
