version: "2"

services:
    #  docker run --name=nginx -d -p 80:80 -p 443:443 \
    #    --volume ~/volumes/nginx/sites:/etc/nginx/sites-enabled:ro \
    #    --volume ~/volumes/nginx/certs:/etc/nginx/certs:ro \
    #    --volume ~/volumes/nginx/www:/var/www \
    #    --link briefmetrics-uwsgi:briefmetrics-uwsgi
    #    shazow/nginx
    nginx:
        image: shazow/nginx
        expose:
            - "80"
            - "443"
        ports:
            - "80:8080"
        volumes:
            - ./nginx/vhosts.d:/etc/nginx/sites-enabled:ro
            - ./nginx/certs:/etc/nginx/certs:ro
            - ./nginx/www:/var/www
        links:
            - briefmetrics:briefmetrics


    #  docker run --name=briefmetrics-uwsgi -d \
    #    --volume ~/volumes/briefmetrics/src:/home/app/src \
    #    --link postgresql:db
    #    shazow/uwsgi-python
    briefmetrics:
        environment:
            - INI_FILE=docker.ini
        image: shazow/python-uwsgi
        volumes:
            - ..:/home/app/src:rw
        expose:
            - "8001"
        links:
            - db:db


    #  docker run --name=db -d shazow/postgresql
    db:
        image: shazow/postgresql
