version: "3"

services:
    #  docker run --name=nginx -d -p 80:80 -p 443:443 \
    #    --volume ~/volumes/nginx/sites:/etc/nginx/sites-enabled:ro \
    #    --volume ~/volumes/nginx/certs:/etc/nginx/certs:ro \
    #    --volume ~/volumes/nginx/www:/var/www \
    #    --link briefmetrics-uwsgi:briefmetrics-uwsgi
    #    nginx:alpine
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./nginx/sites:/etc/nginx/sites-enabled:ro
            - ./nginx/certs:/etc/nginx/certs:ro
            - ../briefmetrics/web/static:/var/www/briefmetrics.com/static
            - ../uploads:/var/www/briefmetrics.com/uploads
        links:
            - briefmetrics-uwsgi:briefmetrics-uwsgi


    #  docker run --name=briefmetrics-uwsgi -d \
    #    --volume ..:/home/app/src \
    #    --link postgresql:db
    #    briefmetrics/uwsgi-python
    briefmetrics-uwsgi:
        container_name: briefmetrics-uwsgi
        environment:
            - INI_FILE=docker.ini
        build: ./uwsgi
        volumes:
            - ..:/home/app/src:rw
            - python-env:/home/app/env:rw
        links:
            - db:db
            - mailserver:mailserver

    #  docker run --name=db -d postgresql:alpine
    db:
        container_name: db
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_DB=db
        volumes:
            - postgresql-data:/var/lib/postgresql

    mailserver:
        container_name: mailserver
        image: namshi/smtp

volumes:
    python-env:
        driver: local
    postgresql-data:
        driver: local
