#!/bin/bash
container_id="briefmetrics-uwsgi"

docker exec -i "${container_id}" bash -c "source env/bin/activate && cd src && make INI_FILE='$INI_FILE' && touch .reload"

if [[ $(docker inspect -f "{{.State.Running}}" "${container_id}") == "true" ]]; then
	echo -e "${CGREEN}Server is happy. :)${CNONE}"
else
	echo -e "${CRED}SERVER IS DOWN! Recent log:${CYELLOW}"
	tail -n40 "$(ls -t /var/log/docker/briefmetrics-uwsgi*.log | head -n1)"
	echo -en "${CNONE}"
fi
